### ISSUE TITLE
Suggestion for readme

### ISSUE THREAD

**Issue by franiglesias** [ohbarye/rails-react-typescript-docker-example#378]
Thank you for this very nice work.

I'd like to suggest including this fragment in the README. This will let you access both frontend and backend.

```
Add the following lines to your `/etc/hosts`:

127.0.0.1 frontend.localhost
127.0.0.1 backend.localhost
```

**Comment by ohbarye** [comment]
Sorry for my late response.
Honestly, I usually don't modify `/etc/hosts` for a specific project, so no motivation to add the fragment. Thanks for your suggestion.
