### ISSUE TITLE
[Feature Request] Replace to `Github Actions` from `CircleCI` (or Add choosable system from them)

### ISSUE THREAD

**Issue by kachick** [ohbarye/rails-react-typescript-docker-example#493]
This project looks so helpful, especially for beginners as me!
And looks keeping to latest framework/language versions, so I admire for your continual working style! (Honestly, I know it from co-worked time at [Quipper](https://www.quipper.com/jp/)  with you 😄 )

I'd like to start my web app project with borrowing this codebase 😋
So how do you think to use `Github Actions` instead of `CircleCI`?
I have very poor knowledges for both platform 😓 
But `Github Actions` looks trendy ✨ Correct?

If you think using `Github Actions` is a good way, adding or replacing it makes my pleasure 😂

**Comment by ohbarye** [comment]
Thank you for your kind remark.

Your suggestion sounds good to me because I personally think GitHub Actions is more handy to set up and integrate through my experience. Please give me some time to migrate from CircleCI to GitHub Actions. 👍

**Comment by kachick** [comment]
😂 🙏

**Comment by ohbarye** [comment]
I hope #496 would be what you've wanted. 👍

**Comment by kachick** [comment]
Oh great! So faster updated!
I'll learn many things from the PR! Thank you!
