### ISSUE TITLE
[Proposal] Be a `template repository` in Github settings

### ISSUE THREAD

**Issue by kachick** [ohbarye/rails-react-typescript-docker-example#497]
https://github.com/ohbarye/rails-react-typescript-docker-example/tree/cf86e0f699ed33ed3ab7df76c4a2ed0aaf77aedf#tldr describes this repository is a `boilerplate`. 

So I think using as a template is useful rather than forking.
How do you feel?

ref:  https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-template-repository

For example, https://github.com/ruby/setup-ruby looks generated from https://github.com/actions/javascript-action

<img width="321" alt="スクリーンショット 2021-03-07 18 47 23" src="https://user-images.githubusercontent.com/1180335/110235824-943f2700-7f75-11eb-9d49-07b3cebc0fcc.png">

<img width="947" alt="スクリーンショット 2021-03-07 18 52 29" src="https://user-images.githubusercontent.com/1180335/110235931-4a0a7580-7f76-11eb-989f-ac9e5b4d6838.png">

**Comment by ohbarye** [comment]
Wow, I didn't know that feature of GitHub. I made this repo a template project. Thanks!

![image](https://user-images.githubusercontent.com/1811616/110237130-6c53c180-7f7d-11eb-9c28-8a1d919719fa.png)

![image](https://user-images.githubusercontent.com/1811616/110237136-72e23900-7f7d-11eb-95bb-5d4c4a3ee669.png)

**Comment by kachick** [comment]
Thank you for the approval!
